version: "3"
services:
  bsc-evm-compatible-bridge-api:
    container_name: bsc-evm-compatible-bridge-api
    build: .
    restart: "on-failure"
    command: ./build/bsc-evm-compatible-bridge-api --scheme=${AP_SCHEME} --host=${AP_HOST} --port=${AP_PORT} --cleanup-timeout=${AP_CLEANUP_TIMEOUT} --secret-name=${SECRET_NAME} --secret-region=${SECRET_REGION}
    env_file:
      - .env
    ports:
      - 8080:8080
