// Code generated by go-swagger; DO NOT EDIT.

package erc_721_swaps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetErc721SwapsHandlerFunc turns a function with the right signature into a get erc721 swaps handler
type GetErc721SwapsHandlerFunc func(GetErc721SwapsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetErc721SwapsHandlerFunc) Handle(params GetErc721SwapsParams) middleware.Responder {
	return fn(params)
}

// GetErc721SwapsHandler interface for that can handle valid get erc721 swaps params
type GetErc721SwapsHandler interface {
	Handle(GetErc721SwapsParams) middleware.Responder
}

// NewGetErc721Swaps creates a new http.Handler for the get erc721 swaps operation
func NewGetErc721Swaps(ctx *middleware.Context, handler GetErc721SwapsHandler) *GetErc721Swaps {
	return &GetErc721Swaps{Context: ctx, Handler: handler}
}

/* GetErc721Swaps swagger:route GET /v1/erc-721-swaps erc_721_swaps getErc721Swaps

Gets list of ERC721 swap.

*/
type GetErc721Swaps struct {
	Context *middleware.Context
	Handler GetErc721SwapsHandler
}

func (o *GetErc721Swaps) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetErc721SwapsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
