// Code generated by go-swagger; DO NOT EDIT.

package erc_1155_swap_pairs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetErc1155SwapPairsHandlerFunc turns a function with the right signature into a get erc1155 swap pairs handler
type GetErc1155SwapPairsHandlerFunc func(GetErc1155SwapPairsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetErc1155SwapPairsHandlerFunc) Handle(params GetErc1155SwapPairsParams) middleware.Responder {
	return fn(params)
}

// GetErc1155SwapPairsHandler interface for that can handle valid get erc1155 swap pairs params
type GetErc1155SwapPairsHandler interface {
	Handle(GetErc1155SwapPairsParams) middleware.Responder
}

// NewGetErc1155SwapPairs creates a new http.Handler for the get erc1155 swap pairs operation
func NewGetErc1155SwapPairs(ctx *middleware.Context, handler GetErc1155SwapPairsHandler) *GetErc1155SwapPairs {
	return &GetErc1155SwapPairs{Context: ctx, Handler: handler}
}

/* GetErc1155SwapPairs swagger:route GET /v1/erc-1155-swap-pairs erc_1155_swap_pairs getErc1155SwapPairs

Gets a list of available ERC1155 swap pairs.

*/
type GetErc1155SwapPairs struct {
	Context *middleware.Context
	Handler GetErc1155SwapPairsHandler
}

func (o *GetErc1155SwapPairs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetErc1155SwapPairsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
