// Code generated by go-swagger; DO NOT EDIT.

// Package restapi BSC <-> EVM Compatible Bridge API
//
//  The BSC <-> EVM Compatible Swap API: provide swap service between BSC and EVM Compatible, which is based on https://github.com/binance-chain/eth-swap-ap
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /
//  Version: 0.1.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
