// Code generated by go-swagger; DO NOT EDIT.

package erc_1155_swaps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetErc1155SwapsHandlerFunc turns a function with the right signature into a get erc1155 swaps handler
type GetErc1155SwapsHandlerFunc func(GetErc1155SwapsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetErc1155SwapsHandlerFunc) Handle(params GetErc1155SwapsParams) middleware.Responder {
	return fn(params)
}

// GetErc1155SwapsHandler interface for that can handle valid get erc1155 swaps params
type GetErc1155SwapsHandler interface {
	Handle(GetErc1155SwapsParams) middleware.Responder
}

// NewGetErc1155Swaps creates a new http.Handler for the get erc1155 swaps operation
func NewGetErc1155Swaps(ctx *middleware.Context, handler GetErc1155SwapsHandler) *GetErc1155Swaps {
	return &GetErc1155Swaps{Context: ctx, Handler: handler}
}

/* GetErc1155Swaps swagger:route GET /v1/erc-1155-swaps erc_1155_swaps getErc1155Swaps

Gets list of ERC1155 swap.

*/
type GetErc1155Swaps struct {
	Context *middleware.Context
	Handler GetErc1155SwapsHandler
}

func (o *GetErc1155Swaps) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetErc1155SwapsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
