// Code generated by go-swagger; DO NOT EDIT.

package svc_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/synycboom/bsc-evm-compatible-bridge-api/models"
)

// GetInfoOKCode is the HTTP code returned for type GetInfoOK
const GetInfoOKCode int = 200

/*GetInfoOK Success

swagger:response getInfoOK
*/
type GetInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceInfo `json:"body,omitempty"`
}

// NewGetInfoOK creates GetInfoOK with default headers values
func NewGetInfoOK() *GetInfoOK {

	return &GetInfoOK{}
}

// WithPayload adds the payload to the get info o k response
func (o *GetInfoOK) WithPayload(payload *models.ServiceInfo) *GetInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get info o k response
func (o *GetInfoOK) SetPayload(payload *models.ServiceInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetInfoBadRequestCode is the HTTP code returned for type GetInfoBadRequest
const GetInfoBadRequestCode int = 400

/*GetInfoBadRequest Bad Request

swagger:response getInfoBadRequest
*/
type GetInfoBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetInfoBadRequest creates GetInfoBadRequest with default headers values
func NewGetInfoBadRequest() *GetInfoBadRequest {

	return &GetInfoBadRequest{}
}

// WithPayload adds the payload to the get info bad request response
func (o *GetInfoBadRequest) WithPayload(payload *models.Error) *GetInfoBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get info bad request response
func (o *GetInfoBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInfoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetInfoInternalServerErrorCode is the HTTP code returned for type GetInfoInternalServerError
const GetInfoInternalServerErrorCode int = 500

/*GetInfoInternalServerError internal server error

swagger:response getInfoInternalServerError
*/
type GetInfoInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetInfoInternalServerError creates GetInfoInternalServerError with default headers values
func NewGetInfoInternalServerError() *GetInfoInternalServerError {

	return &GetInfoInternalServerError{}
}

// WithPayload adds the payload to the get info internal server error response
func (o *GetInfoInternalServerError) WithPayload(payload *models.Error) *GetInfoInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get info internal server error response
func (o *GetInfoInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
