// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Erc1155Swaps erc1155 swaps
//
// swagger:model Erc1155Swaps
type Erc1155Swaps struct {

	// erc 1155 swaps
	Erc1155Swaps []*Erc1155Swap `json:"erc_1155_swaps"`

	// total
	Total int64 `json:"total"`
}

// Validate validates this erc1155 swaps
func (m *Erc1155Swaps) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErc1155Swaps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Erc1155Swaps) validateErc1155Swaps(formats strfmt.Registry) error {
	if swag.IsZero(m.Erc1155Swaps) { // not required
		return nil
	}

	for i := 0; i < len(m.Erc1155Swaps); i++ {
		if swag.IsZero(m.Erc1155Swaps[i]) { // not required
			continue
		}

		if m.Erc1155Swaps[i] != nil {
			if err := m.Erc1155Swaps[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("erc_1155_swaps" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("erc_1155_swaps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this erc1155 swaps based on the context it is used
func (m *Erc1155Swaps) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateErc1155Swaps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Erc1155Swaps) contextValidateErc1155Swaps(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Erc1155Swaps); i++ {

		if m.Erc1155Swaps[i] != nil {
			if err := m.Erc1155Swaps[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("erc_1155_swaps" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("erc_1155_swaps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Erc1155Swaps) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Erc1155Swaps) UnmarshalBinary(b []byte) error {
	var res Erc1155Swaps
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
