// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Erc721Swaps erc721 swaps
//
// swagger:model Erc721Swaps
type Erc721Swaps struct {

	// erc 721 swaps
	Erc721Swaps []*Erc721Swap `json:"erc_721_swaps"`

	// total
	Total int64 `json:"total"`
}

// Validate validates this erc721 swaps
func (m *Erc721Swaps) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErc721Swaps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Erc721Swaps) validateErc721Swaps(formats strfmt.Registry) error {
	if swag.IsZero(m.Erc721Swaps) { // not required
		return nil
	}

	for i := 0; i < len(m.Erc721Swaps); i++ {
		if swag.IsZero(m.Erc721Swaps[i]) { // not required
			continue
		}

		if m.Erc721Swaps[i] != nil {
			if err := m.Erc721Swaps[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("erc_721_swaps" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("erc_721_swaps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this erc721 swaps based on the context it is used
func (m *Erc721Swaps) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateErc721Swaps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Erc721Swaps) contextValidateErc721Swaps(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Erc721Swaps); i++ {

		if m.Erc721Swaps[i] != nil {
			if err := m.Erc721Swaps[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("erc_721_swaps" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("erc_721_swaps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Erc721Swaps) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Erc721Swaps) UnmarshalBinary(b []byte) error {
	var res Erc721Swaps
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
