// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Erc721Swap erc721 swap
//
// swagger:model Erc721Swap
type Erc721Swap struct {

	// base uri
	BaseURI string `json:"base_uri"`

	// created at
	CreatedAt string `json:"created_at"`

	// dst chain id
	DstChainID string `json:"dst_chain_id"`

	// dst token addr
	DstTokenAddr string `json:"dst_token_addr"`

	// dst token name
	DstTokenName string `json:"dst_token_name"`

	// fill tx hash
	FillTxHash string `json:"fill_tx_hash"`

	// recipient
	Recipient string `json:"recipient"`

	// request tx hash
	RequestTxHash string `json:"request_tx_hash"`

	// sender
	Sender string `json:"sender"`

	// src chain id
	SrcChainID string `json:"src_chain_id"`

	// src token addr
	SrcTokenAddr string `json:"src_token_addr"`

	// src token name
	SrcTokenName string `json:"src_token_name"`

	// state
	State string `json:"state"`

	// swap direction
	SwapDirection string `json:"swap_direction"`

	// token id
	TokenID string `json:"token_id"`

	// token uri
	TokenURI string `json:"token_uri"`

	// updated at
	UpdatedAt string `json:"updated_at"`
}

// Validate validates this erc721 swap
func (m *Erc721Swap) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this erc721 swap based on context it is used
func (m *Erc721Swap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Erc721Swap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Erc721Swap) UnmarshalBinary(b []byte) error {
	var res Erc721Swap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
